name: Clone Private Repo
on:
  workflow_dispatch:
# permissions:
#   contents: write
jobs:
  clone-sample:
    runs-on: ubuntu-latest
    steps:
    - name: generate token
      id: app-token
      uses: actions/create-github-app-token@v3
      with:
        client-id: ${{ secrets.TOKEN_GEN_APP_CLIENT_ID }}
        private-key: ${{ secrets.TOKEN_GEN_PRIVATE_KEY }}
        repository: jyuzen-sw/homepage

    - name: Checkout private repo
      uses: actions/checkout@v4
      with:
        repository: jyuzen-sw/homepage
        token: ${{ steps.app-token.outputs.token }}
    
    - name: DEBUG dump file list
      run: ls -al